//go:build linux && cgo

package drawer

// The real panel: an undecorated GTK3 toplevel hosting one WebKitWebView,
// linked directly against the system webkit2gtk-4.1 + gtk+-3.0 through
// pkg-config (hand-rolled cgo, the internal/player idiom; no Go modules).
//
// Threading contract: gtk_init + gtk_main run on ONE dedicated goroutine with
// the OS thread locked; every later GTK/WebKit call is marshaled onto that
// thread through g_idle_add draining the gtkCalls channel. fyne/systray on
// Linux speaks DBus StatusNotifier and runs no GTK loop of its own, so the two
// coexist (verified at runtime on GNOME/X11).

/*
#cgo pkg-config: webkit2gtk-4.1 gtk+-3.0

#include <stdlib.h>
#include <gtk/gtk.h>
#include <webkit2/webkit2.h>

// Callbacks exported from callbacks_linux.go (declaration-only there; the
// definitions are generated by cgo).
extern gboolean fipDrawerIdle(gpointer data);
extern void fipDrawerScriptMessage(WebKitUserContentManager *m, WebKitJavascriptResult *r, gpointer data);
extern gboolean fipDrawerKeyPress(GtkWidget *w, GdkEventKey *e, gpointer data);
extern gboolean fipDrawerDelete(GtkWidget *w, GdkEvent *e, gpointer data);

static void fip_idle_add(void) { g_idle_add(fipDrawerIdle, NULL); }

// fip_build assembles the resident window once, on the GTK thread: an
// undecorated, keep-above utility toplevel holding the webview, with the "fip"
// script message channel registered and the page loaded from the embedded
// string. Built hidden; showing is fip_present.
static GtkWidget *fip_build(WebKitWebView **out_view, const char *html, int width, int height) {
	GtkWidget *win = gtk_window_new(GTK_WINDOW_TOPLEVEL);
	gtk_window_set_title(GTK_WINDOW(win), "le panneau · FIP");
	gtk_window_set_decorated(GTK_WINDOW(win), FALSE);
	gtk_window_set_skip_taskbar_hint(GTK_WINDOW(win), TRUE);
	gtk_window_set_skip_pager_hint(GTK_WINDOW(win), TRUE);
	gtk_window_set_keep_above(GTK_WINDOW(win), TRUE);
	// The panel follows you: visible on every workspace, not only the one it
	// was invoked from. Re-asserted at each present, as some WMs drop the
	// sticky bit across hide/show cycles.
	gtk_window_stick(GTK_WINDOW(win));
	gtk_window_set_type_hint(GTK_WINDOW(win), GDK_WINDOW_TYPE_HINT_UTILITY);
	gtk_window_set_default_size(GTK_WINDOW(win), width, height);

	WebKitUserContentManager *ucm = webkit_user_content_manager_new();
	webkit_user_content_manager_register_script_message_handler(ucm, "fip");
	GtkWidget *view = webkit_web_view_new_with_user_content_manager(ucm);

	// Surface the page's console (including uncaught JS exceptions) on the
	// process stdout: a render bug in the panel must be observable from the
	// app log and the `fipindicateur drawer` harness, never a silent blank.
	webkit_settings_set_enable_write_console_messages_to_stdout(
		webkit_web_view_get_settings(WEBKIT_WEB_VIEW(view)), TRUE);

	// Transparent window + webview background when a compositor is there, so
	// the page's own rounded corners and shadow show through; without one the
	// panel stays a clean opaque rectangle. app_paintable is the load-bearing
	// third leg: without it GTK fills the toplevel with the theme background
	// even under an RGBA visual, which reads as opaque square corners around
	// the page's rounded panel.
	GdkScreen *screen = gtk_widget_get_screen(win);
	GdkVisual *visual = gdk_screen_get_rgba_visual(screen);
	if (visual != NULL && gdk_screen_is_composited(screen)) {
		gtk_widget_set_visual(win, visual);
		gtk_widget_set_app_paintable(win, TRUE);
		GdkRGBA transparent = {1.0, 1.0, 1.0, 0.0};
		webkit_web_view_set_background_color(WEBKIT_WEB_VIEW(view), &transparent);
	}

	// No focus-out handler on purpose: the panel STAYS open while other
	// windows take focus (it floats keep-above). It hides only on Escape, the
	// page's own close affordance, or the tray menu toggle.
	gtk_container_add(GTK_CONTAINER(win), view);
	g_signal_connect(ucm, "script-message-received::fip", G_CALLBACK(fipDrawerScriptMessage), NULL);
	g_signal_connect(win, "key-press-event", G_CALLBACK(fipDrawerKeyPress), NULL);
	g_signal_connect(win, "delete-event", G_CALLBACK(fipDrawerDelete), NULL);
	gtk_widget_show(view);

	webkit_web_view_load_html(WEBKIT_WEB_VIEW(view), html, "about:blank");
	*out_view = WEBKIT_WEB_VIEW(view);
	return win;
}

// fip_present shows the panel at the TOP-RIGHT of the primary monitor's work
// area: right edge minus the window width minus a small margin, a margin from
// the top (under the GNOME top bar; the WM clamps to the work area anyway).
// The width is fixed (only the height is content-driven), so the x position
// never needs recomputing on resize.
static void fip_present(GtkWidget *win, int width, int margin) {
	gtk_widget_show(win);
	gtk_window_stick(GTK_WINDOW(win)); // see fip_build: survive hide/show
	GdkDisplay *dpy = gtk_widget_get_display(win);
	GdkMonitor *mon = gdk_display_get_primary_monitor(dpy);
	if (mon == NULL) mon = gdk_display_get_monitor(dpy, 0);
	GdkRectangle wa = {0, 0, 1280, 720}; // last-resort fallback geometry
	if (mon != NULL) gdk_monitor_get_workarea(mon, &wa);
	gtk_window_move(GTK_WINDOW(win), wa.x + wa.width - width - margin, wa.y + margin);
	gtk_window_present(GTK_WINDOW(win));
}

static void fip_resize(GtkWidget *win, int w, int h) {
	gtk_window_resize(GTK_WINDOW(win), w, h);
}

static void fip_eval(WebKitWebView *view, const char *script) {
	webkit_web_view_evaluate_javascript(view, script, -1, NULL, NULL, NULL, NULL, NULL);
}
*/
import "C"

import (
	"encoding/json"
	"errors"
	"log"
	"runtime"
	"sync"
	"unsafe"
)

// Available reports whether this build carries the real panel. True here
// (linux && cgo); the stub is false, and the tray keeps its volume submenu.
const Available = true

const (
	panelWidth  = 380
	panelMargin = 12 // gap from the work area's top-right corner
	minHeight   = 200
	maxHeight   = 800
)

// gtkCalls carries closures to the GTK thread: fip_idle_add schedules one
// fipDrawerIdle dispatch per queued closure (g_idle_add is thread-safe, so
// this is the whole cross-thread story).
var gtkCalls = make(chan func(), 64)

// current is the process's one drawer, the target of the C signal callbacks
// (which carry no useful user_data across cgo). Guarded by currentMu.
var (
	currentMu sync.Mutex
	current   *Drawer
)

func currentDrawer() *Drawer {
	currentMu.Lock()
	defer currentMu.Unlock()
	return current
}

// Drawer is the resident panel window. Build once (first Show), then hide and
// re-present: reopening is instant. All exported methods are safe from any
// goroutine.
type Drawer struct {
	onCommand func(Command)
	onHide    func()

	mu          sync.Mutex
	lastState   State
	hasState    bool
	pendingView string // view requested before the page could take it
	started     bool   // GTK goroutine launched (protects reading ready/initErr)

	startOnce sync.Once
	ready     chan struct{}
	initErr   error

	// GTK-thread-only state after ready closes.
	win       *C.GtkWidget
	view      *C.WebKitWebView
	pageReady bool // the page ran its script and can accept fipState pushes
}

// New prepares a drawer. onCommand receives the page's user actions on a
// fresh goroutine (never the GTK thread); onHide (optional) fires whenever
// the panel hides (Escape, the page's close button, or an explicit Hide).
func New(onCommand func(Command), onHide func()) *Drawer {
	d := &Drawer{onCommand: onCommand, onHide: onHide, ready: make(chan struct{})}
	currentMu.Lock()
	current = d
	currentMu.Unlock()
	return d
}

// ensureStarted launches the dedicated GTK goroutine once and waits for the
// window to be built (or gtk_init to fail: headless, no DISPLAY).
func (d *Drawer) ensureStarted() error {
	d.startOnce.Do(func() {
		d.mu.Lock()
		d.started = true
		d.mu.Unlock()
		go func() {
			// GTK requires all its calls on one OS thread, forever.
			runtime.LockOSThread()
			if C.gtk_init_check(nil, nil) == 0 {
				d.initErr = errors.New("drawer: gtk_init a échoué (pas d'affichage ?)")
				close(d.ready)
				return
			}
			html := C.CString(pageHTML)
			var view *C.WebKitWebView
			d.win = C.fip_build(&view, html, panelWidth, 520)
			C.free(unsafe.Pointer(html)) // load_html copied it
			d.view = view
			close(d.ready)
			C.gtk_main()
		}()
	})
	<-d.ready
	return d.initErr
}

// Show builds the window on first use, pushes the given state and presents
// the panel at the top-right of the primary monitor's work area.
func (d *Drawer) Show(state State) error {
	d.mu.Lock()
	d.lastState = state
	d.hasState = true
	d.mu.Unlock()
	if err := d.ensureStarted(); err != nil {
		return err
	}
	d.runOnGTK(func() {
		d.evalStateLocked()
		C.fip_present(d.win, panelWidth, panelMargin)
	})
	return nil
}

// Push updates the page's state (visible or not) so the next look is always
// current. A no-op until the first Show built the window.
func (d *Drawer) Push(state State) {
	d.mu.Lock()
	d.lastState = state
	d.hasState = true
	started := d.started
	d.mu.Unlock()
	if !started {
		return
	}
	select {
	case <-d.ready:
	default:
		return // still initializing; Show will push
	}
	if d.initErr != nil {
		return
	}
	d.runOnGTK(func() { d.evalStateLocked() })
}

// SetView asks the page to switch to a named view ("main", "history",
// "settings"). Sticky until the page has run its script: a view requested
// alongside the very first Show is applied right after the initial state
// lands, so a right click can open straight onto Réglages.
func (d *Drawer) SetView(view string) {
	d.mu.Lock()
	d.pendingView = view
	started := d.started
	d.mu.Unlock()
	if !started {
		return // applied by the page's "ready" dispatch after Show
	}
	select {
	case <-d.ready:
	default:
		return
	}
	if d.initErr != nil {
		return
	}
	d.runOnGTK(func() { d.evalViewLocked() })
}

// evalViewLocked pushes the pending view request, if any. GTK thread only
// (the Locked suffix follows evalStateLocked's convention).
func (d *Drawer) evalViewLocked() {
	if !d.pageReady {
		return // the "ready" dispatch will re-run this
	}
	d.mu.Lock()
	view := d.pendingView
	d.pendingView = ""
	d.mu.Unlock()
	if view == "" {
		return
	}
	data, err := json.Marshal(view)
	if err != nil {
		return
	}
	script := C.CString("window.fipView && window.fipView(" + string(data) + ");")
	C.fip_eval(d.view, script)
	C.free(unsafe.Pointer(script))
}

// Eval runs a script in the page once it is ready. Test/dev plumbing (the
// selftest drives the page's buttons through it); the app itself pushes state
// only through Push/SetView.
func (d *Drawer) Eval(script string) {
	d.mu.Lock()
	started := d.started
	d.mu.Unlock()
	if !started {
		return
	}
	select {
	case <-d.ready:
	default:
		return
	}
	if d.initErr != nil {
		return
	}
	d.runOnGTK(func() {
		if !d.pageReady {
			return
		}
		cs := C.CString(script)
		C.fip_eval(d.view, cs)
		C.free(unsafe.Pointer(cs))
	})
}

// SetWindowTitle renames the toplevel. The dev harness uses it so a leftover
// mock window can never pass for the real panel.
func (d *Drawer) SetWindowTitle(title string) {
	d.mu.Lock()
	started := d.started
	d.mu.Unlock()
	if !started {
		return
	}
	select {
	case <-d.ready:
	default:
		return
	}
	if d.initErr != nil {
		return
	}
	t := C.CString(title)
	d.runOnGTK(func() {
		C.gtk_window_set_title((*C.GtkWindow)(unsafe.Pointer(d.win)), t)
		C.free(unsafe.Pointer(t))
	})
}

// Hide withdraws the panel (it stays resident for an instant reopen).
func (d *Drawer) Hide() {
	d.mu.Lock()
	started := d.started
	d.mu.Unlock()
	if !started || d.initErr != nil {
		return
	}
	d.runOnGTK(func() { d.hideOnGTK() })
}

// runOnGTK queues fn for the GTK thread. Safe from any goroutine.
func (d *Drawer) runOnGTK(fn func()) {
	gtkCalls <- fn
	C.fip_idle_add()
}

// evalStateLocked pushes the last state into the page. GTK thread only. The
// JSON is a valid JS literal (encoding/json escapes the U+2028/29 hazards),
// so it is injected verbatim into the window.fipState call.
func (d *Drawer) evalStateLocked() {
	if !d.pageReady {
		return // the page will ask (action "ready") once its script runs
	}
	d.mu.Lock()
	has := d.hasState
	state := d.lastState
	d.mu.Unlock()
	if !has {
		return
	}
	data, err := json.Marshal(state)
	if err != nil {
		log.Printf("drawer: marshal state: %v", err)
		return
	}
	script := C.CString("window.fipState(" + string(data) + ");")
	C.fip_eval(d.view, script)
	C.free(unsafe.Pointer(script))
}

// hideOnGTK hides the window and fires onHide. GTK thread only.
func (d *Drawer) hideOnGTK() {
	C.gtk_widget_hide(d.win)
	if d.onHide != nil {
		go d.onHide()
	}
}

// dispatch routes a page message. Internal actions (ready/height/hide) are
// the drawer's own plumbing; everything else is a user command handed to the
// app off the GTK thread. GTK thread only.
func (d *Drawer) dispatch(cmd Command) {
	switch cmd.Action {
	case "ready":
		d.pageReady = true
		d.evalStateLocked()
		d.evalViewLocked()
	case "height":
		// Content-driven height, reported by the page after each render.
		h := cmd.Value
		if h < minHeight {
			h = minHeight
		}
		if h > maxHeight {
			h = maxHeight
		}
		C.fip_resize(d.win, panelWidth, C.int(h))
	case "hide":
		d.hideOnGTK()
	default:
		if d.onCommand != nil {
			go d.onCommand(cmd)
		}
	}
}
